import { Controller, Get, Post, Put, Delete, Body, Param, Query, UseGuards } from '@nestjs/common';
import { ApiTags, ApiOperation, ApiBearerAuth, ApiQuery } from '@nestjs/swagger';
import { ActionCardService } from './action-card.service';
import { JwtAuthGuard } from '../../common/guards/jwt-auth.guard';
import { User, RequestUser } from '../../common/decorators/user.decorator';
import { CreateActionCardDto, UpdateActionCardDto, BulkSyncCardsDto } from './dto';

@ApiTags('action-cards')
@Controller('action-cards')
@UseGuards(JwtAuthGuard)
@ApiBearerAuth()
export class ActionCardController {
  constructor(private cardService: ActionCardService) {}

  @Post()
  @ApiOperation({ summary: 'Create an action card (typically from AI service)' })
  create(@User() user: RequestUser, @Body() dto: CreateActionCardDto) {
    return this.cardService.create(user.id, dto);
  }

  @Post('sync')
  @ApiOperation({ summary: 'Bulk sync cards generated by AI service' })
  sync(@User() user: RequestUser, @Body() dto: BulkSyncCardsDto) {
    return this.cardService.bulkSync(user.id, dto);
  }

  @Get()
  @ApiOperation({ summary: 'List action cards' })
  @ApiQuery({ name: 'status', required: false, type: String })
  @ApiQuery({ name: 'priority', required: false, type: String })
  findAll(
    @User() user: RequestUser,
    @Query('status') status?: string,
    @Query('priority') priority?: string,
  ) {
    return this.cardService.findAll(user.id, { status, priority });
  }

  @Get(':id')
  @ApiOperation({ summary: 'Get action card by ID' })
  findOne(@User() user: RequestUser, @Param('id') id: string) {
    return this.cardService.findOne(user.id, id);
  }

  @Put(':id')
  @ApiOperation({ summary: 'Update action card' })
  update(@User() user: RequestUser, @Param('id') id: string, @Body() dto: UpdateActionCardDto) {
    return this.cardService.update(user.id, id, dto);
  }

  @Post(':id/dismiss')
  @ApiOperation({ summary: 'Dismiss action card' })
  dismiss(@User() user: RequestUser, @Param('id') id: string) {
    return this.cardService.dismiss(user.id, id);
  }

  @Post(':id/complete')
  @ApiOperation({ summary: 'Mark action card as completed' })
  complete(@User() user: RequestUser, @Param('id') id: string) {
    return this.cardService.complete(user.id, id);
  }

  @Delete(':id')
  @ApiOperation({ summary: 'Delete action card' })
  delete(@User() user: RequestUser, @Param('id') id: string) {
    return this.cardService.delete(user.id, id);
  }
}
